### PR TITLE
Grab contentBlocks from output of htmlToDraft

### PR DESCRIPTION
**Pull request by andrewnoyes**
Example in playground code was correct. Readme just missed a step.

### CODE REVIEW

**Comment by jpuri** [comment]
Hey @andrewnoyes can you please resolve the conflict.

**Comment by andrewnoyes** [comment]
@jpuri 👍

**Comment by kalombos** [comment]
Looks like me and @andrewnoyes made the same fix at the same time:)

**Comment by jpuri** [comment]
Yep @kalombos co-incident 😄  !
They are similar though not exactly same.

**Pull request merged**
